//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Requests
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// A paginated list of items. The `nextPage` field is omitted if there are no more pages available.
    /// </summary>
    public class ListTicketsResponseBody
    {

        [JsonProperty("items")]
        public List<Ticket> Items { get; set; } = default!;

        [JsonProperty("nextPage")]
        public ItemListNextPage? NextPage { get; set; }
    }
}