//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Errors
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;

    public class PatchWalletValidationErrorPayload
    {
        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("status")]
        public string? Status { get; set; }

        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("metadata")]
        public string? Metadata { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    public class PatchWalletValidationError : MoovException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public PatchWalletValidationErrorPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use PatchWalletValidationError.Payload.Name instead.")]
        public string? Name { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use PatchWalletValidationError.Payload.Status instead.")]
        public string? Status { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use PatchWalletValidationError.Payload.Description instead.")]
        public string? Description { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use PatchWalletValidationError.Payload.Metadata instead.")]
        public string? Metadata { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use PatchWalletValidationError.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public PatchWalletValidationError(
            PatchWalletValidationErrorPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base("API error occurred", request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Name = payload.Name;
           Status = payload.Status;
           Description = payload.Description;
           Metadata = payload.Metadata;
           HttpMeta = payload.HttpMeta;
           #pragma warning restore CS0618
        }
    }
}