//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk
{
    using Moov.Sdk.Hooks;
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Models.Errors;
    using Moov.Sdk.Models.Requests;
    using Moov.Sdk.Utils;
    using Moov.Sdk.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading;
    using System.Threading.Tasks;

    public interface IInvoices
    {
        /// <summary>
        /// Create an invoice for a Moov account.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.write` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="body">A <see cref="CreateInvoice"/> parameter.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="CreateInvoiceResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/> or <paramref name="body"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="GenericError">The server could not understand the request due to invalid syntax. Thrown when the API returns a 400 or 409 response.</exception>
        /// <exception cref="CreateInvoiceError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<CreateInvoiceResponse> CreateInvoiceAsync(
            string accountID,
            CreateInvoice body,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        );

        /// <summary>
        /// List all the invoices created under a Moov account.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.read` scope.
        /// </summary>
        /// <param name="request">A <see cref="ListInvoicesRequest"/> parameter.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="ListInvoicesResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="ListInvoicesValidationError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<ListInvoicesResponse> ListInvoicesAsync(
            ListInvoicesRequest request,
            CancellationToken? cancellationToken = null
        );

        /// <summary>
        /// Retrieve an invoice by ID.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.read` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="GetInvoiceResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/> or <paramref name="invoiceID"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<GetInvoiceResponse> GetInvoiceAsync(
            string accountID,
            string invoiceID,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        );

        /// <summary>
        /// Updates an invoice.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.write` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="body">A <see cref="UpdateInvoice"/> parameter.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="UpdateInvoiceResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/>, <paramref name="invoiceID"/> or <paramref name="body"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="GenericError">The server could not understand the request due to invalid syntax. Thrown when the API returns a 400 or 409 response.</exception>
        /// <exception cref="UpdateInvoiceError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<UpdateInvoiceResponse> UpdateInvoiceAsync(
            string accountID,
            string invoiceID,
            UpdateInvoice body,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        );

        /// <summary>
        /// Creates a payment resource to represent that an invoice was paid outside of the Moov platform.<br/>
        /// If a payment link was created for the invoice, the corresponding payment link is canceled, but a receipt is still sent.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.write` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="body">A <see cref="CreateInvoicePayment"/> parameter.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="CreateInvoicePaymentResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/>, <paramref name="invoiceID"/> or <paramref name="body"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="GenericError">The server could not understand the request due to invalid syntax. Thrown when the API returns a 400 or 409 response.</exception>
        /// <exception cref="CreateInvoicePaymentError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<CreateInvoicePaymentResponse> CreateInvoicePaymentAsync(
            string accountID,
            string invoiceID,
            CreateInvoicePayment body,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        );

        /// <summary>
        /// List all the payments made towards an invoice.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.read` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="ListInvoicePaymentsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/> or <paramref name="invoiceID"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<ListInvoicePaymentsResponse> ListInvoicePaymentsAsync(
            string accountID,
            string invoiceID,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        );
    }

    public class Invoices: IInvoices
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        public Invoices(SDKConfig config)
        {
            SDKConfiguration = config;
        }

        /// <summary>
        /// Create an invoice for a Moov account.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.write` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="body">A <see cref="CreateInvoice"/> parameter.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="CreateInvoiceResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/> or <paramref name="body"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="GenericError">The server could not understand the request due to invalid syntax. Thrown when the API returns a 400 or 409 response.</exception>
        /// <exception cref="CreateInvoiceError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<CreateInvoiceResponse> CreateInvoiceAsync(
            string accountID,
            CreateInvoice body,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        )
        {
            if (accountID == null) throw new ArgumentNullException(nameof(accountID));
            if (body == null) throw new ArgumentNullException(nameof(body));

            var request = new CreateInvoiceRequest()
            {
                AccountID = accountID,
                Body = body,
                XMoovVersion = xMoovVersion,
            };
            request.XMoovVersion ??= SDKConfiguration.XMoovVersion;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/accounts/{accountID}/invoices", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "createInvoice", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 201)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    Invoice obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<Invoice>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into Invoice.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new CreateInvoiceResponse()
                    {
                        HttpMeta = new Models.Components.HTTPMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.Invoice = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 409}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GenericErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<GenericErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GenericErrorPayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new GenericError(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 422)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    CreateInvoiceErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<CreateInvoiceErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into CreateInvoiceErrorPayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new CreateInvoiceError(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{401, 403, 404, 429}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{500, 504}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// List all the invoices created under a Moov account.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.read` scope.
        /// </summary>
        /// <param name="request">A <see cref="ListInvoicesRequest"/> parameter.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="ListInvoicesResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="ListInvoicesValidationError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<ListInvoicesResponse> ListInvoicesAsync(
            ListInvoicesRequest request,
            CancellationToken? cancellationToken = null
        )
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.XMoovVersion ??= SDKConfiguration.XMoovVersion;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/accounts/{accountID}/invoices", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "listInvoices", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    List<Invoice> obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<List<Invoice>>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into List<Invoice>.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new ListInvoicesResponse()
                    {
                        HttpMeta = new Models.Components.HTTPMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.Invoices = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 422)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ListInvoicesValidationErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<ListInvoicesValidationErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ListInvoicesValidationErrorPayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new ListInvoicesValidationError(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{401, 403, 429}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{500, 504}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Retrieve an invoice by ID.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.read` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="GetInvoiceResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/> or <paramref name="invoiceID"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<GetInvoiceResponse> GetInvoiceAsync(
            string accountID,
            string invoiceID,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        )
        {
            if (accountID == null) throw new ArgumentNullException(nameof(accountID));
            if (invoiceID == null) throw new ArgumentNullException(nameof(invoiceID));

            var request = new GetInvoiceRequest()
            {
                AccountID = accountID,
                InvoiceID = invoiceID,
                XMoovVersion = xMoovVersion,
            };
            request.XMoovVersion ??= SDKConfiguration.XMoovVersion;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/accounts/{accountID}/invoices/{invoiceID}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "getInvoice", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    Invoice obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<Invoice>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into Invoice.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new GetInvoiceResponse()
                    {
                        HttpMeta = new Models.Components.HTTPMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.Invoice = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{401, 403, 404, 429}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{500, 504}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Updates an invoice.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.write` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="body">A <see cref="UpdateInvoice"/> parameter.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="UpdateInvoiceResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/>, <paramref name="invoiceID"/> or <paramref name="body"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="GenericError">The server could not understand the request due to invalid syntax. Thrown when the API returns a 400 or 409 response.</exception>
        /// <exception cref="UpdateInvoiceError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<UpdateInvoiceResponse> UpdateInvoiceAsync(
            string accountID,
            string invoiceID,
            UpdateInvoice body,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        )
        {
            if (accountID == null) throw new ArgumentNullException(nameof(accountID));
            if (invoiceID == null) throw new ArgumentNullException(nameof(invoiceID));
            if (body == null) throw new ArgumentNullException(nameof(body));

            var request = new UpdateInvoiceRequest()
            {
                AccountID = accountID,
                InvoiceID = invoiceID,
                Body = body,
                XMoovVersion = xMoovVersion,
            };
            request.XMoovVersion ??= SDKConfiguration.XMoovVersion;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/accounts/{accountID}/invoices/{invoiceID}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Patch, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "updateInvoice", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    Invoice obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<Invoice>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into Invoice.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new UpdateInvoiceResponse()
                    {
                        HttpMeta = new Models.Components.HTTPMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.Invoice = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 409}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GenericErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<GenericErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GenericErrorPayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new GenericError(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 422)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    UpdateInvoiceErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<UpdateInvoiceErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into UpdateInvoiceErrorPayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new UpdateInvoiceError(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{401, 403, 404, 429}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{500, 504}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Creates a payment resource to represent that an invoice was paid outside of the Moov platform.<br/>
        /// If a payment link was created for the invoice, the corresponding payment link is canceled, but a receipt is still sent.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.write` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="body">A <see cref="CreateInvoicePayment"/> parameter.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="CreateInvoicePaymentResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/>, <paramref name="invoiceID"/> or <paramref name="body"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="GenericError">The server could not understand the request due to invalid syntax. Thrown when the API returns a 400 or 409 response.</exception>
        /// <exception cref="CreateInvoicePaymentError">The request was well-formed, but the contents failed validation. Check the request for missing or invalid fields. Thrown when the API returns a 422 response.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<CreateInvoicePaymentResponse> CreateInvoicePaymentAsync(
            string accountID,
            string invoiceID,
            CreateInvoicePayment body,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        )
        {
            if (accountID == null) throw new ArgumentNullException(nameof(accountID));
            if (invoiceID == null) throw new ArgumentNullException(nameof(invoiceID));
            if (body == null) throw new ArgumentNullException(nameof(body));

            var request = new CreateInvoicePaymentRequest()
            {
                AccountID = accountID,
                InvoiceID = invoiceID,
                Body = body,
                XMoovVersion = xMoovVersion,
            };
            request.XMoovVersion ??= SDKConfiguration.XMoovVersion;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/accounts/{accountID}/invoices/{invoiceID}/payments", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "createInvoicePayment", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    InvoicePayment obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<InvoicePayment>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into InvoicePayment.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new CreateInvoicePaymentResponse()
                    {
                        HttpMeta = new Models.Components.HTTPMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.InvoicePayment = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{400, 409}.Contains(responseStatusCode))
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GenericErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<GenericErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GenericErrorPayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new GenericError(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode == 422)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    CreateInvoicePaymentErrorPayload payload;
                    try
                    {
                        payload = ResponseBodyDeserializer.DeserializeNotNull<CreateInvoicePaymentErrorPayload>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into CreateInvoicePaymentErrorPayload.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    payload.HttpMeta = new Models.Components.HTTPMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    };

                    throw new CreateInvoicePaymentError(payload, httpRequest, httpResponse, httpResponseBody);
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{401, 403, 404, 429}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{500, 504}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// List all the payments made towards an invoice.<br/>
        /// <br/>
        /// To access this endpoint using an <a href="https://docs.moov.io/api/authentication/access-tokens/">access token</a>
        /// you'll need to specify the `/accounts/{accountID}/invoices.read` scope.
        /// </summary>
        /// <param name="accountID">Description not available.</param>
        /// <param name="invoiceID">Description not available.</param>
        /// <param name="xMoovVersion">
        /// Specify an API version.<br/>
        /// <br/>
        /// API versioning follows the format `vYYYY.QQ.BB`, where <br/>
        ///   - `YYYY` is the year<br/>
        ///   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)<br/>
        ///   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. <br/>
        ///     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.<br/>
        /// <br/>
        /// The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.<br/>
        /// When no version is specified, the API defaults to `v2024.01.00`.
        /// </param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="ListInvoicePaymentsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">One of <paramref name="accountID"/> or <paramref name="invoiceID"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<ListInvoicePaymentsResponse> ListInvoicePaymentsAsync(
            string accountID,
            string invoiceID,
            string? xMoovVersion = null,
            CancellationToken? cancellationToken = null
        )
        {
            if (accountID == null) throw new ArgumentNullException(nameof(accountID));
            if (invoiceID == null) throw new ArgumentNullException(nameof(invoiceID));

            var request = new ListInvoicePaymentsRequest()
            {
                AccountID = accountID,
                InvoiceID = invoiceID,
                XMoovVersion = xMoovVersion,
            };
            request.XMoovVersion ??= SDKConfiguration.XMoovVersion;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/accounts/{accountID}/invoices/{invoiceID}/payments", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "listInvoicePayments", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    List<InvoicePayment> obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<List<InvoicePayment>>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into List<InvoicePayment>.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new ListInvoicePaymentsResponse()
                    {
                        HttpMeta = new Models.Components.HTTPMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.InvoicePayments = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{401, 403, 429}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(new List<int>{500, 504}.Contains(responseStatusCode))
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

    }
}