//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Errors
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;

    public class UpdateIssuedCardErrorPayload
    {
        [JsonProperty("state")]
        public string? State { get; set; }

        [JsonProperty("memo")]
        public string? Memo { get; set; }

        [JsonProperty("authorizedUser")]
        public CreateAuthorizedUserError? AuthorizedUser { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    public class UpdateIssuedCardError : MoovException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public UpdateIssuedCardErrorPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use UpdateIssuedCardError.Payload.State instead.")]
        public string? State { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use UpdateIssuedCardError.Payload.Memo instead.")]
        public string? Memo { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use UpdateIssuedCardError.Payload.AuthorizedUser instead.")]
        public CreateAuthorizedUserError? AuthorizedUser { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use UpdateIssuedCardError.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public UpdateIssuedCardError(
            UpdateIssuedCardErrorPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base("API error occurred", request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           State = payload.State;
           Memo = payload.Memo;
           AuthorizedUser = payload.AuthorizedUser;
           HttpMeta = payload.HttpMeta;
           #pragma warning restore CS0618
        }
    }

}