//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    
    public class AsyncTransfer
    {

        [JsonProperty("transferID")]
        public string TransferID { get; set; } = default!;

        [JsonProperty("createdOn")]
        public DateTime CreatedOn { get; set; } = default!;
    }
}