//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum BankAccountWaitFor
    {
        [JsonProperty("payment-method")]
        PaymentMethod,
        [JsonProperty("rail-response")]
        RailResponse,
    }

    public static class BankAccountWaitForExtension
    {
        public static string Value(this BankAccountWaitFor value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static BankAccountWaitFor ToEnum(this string value)
        {
            foreach(var field in typeof(BankAccountWaitFor).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is BankAccountWaitFor)
                    {
                        return (BankAccountWaitFor)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum BankAccountWaitFor");
        }
    }

}