//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Details of a specific interchange program fee.
    /// </summary>
    public class BillingInterchangeProgramFee
    {

        /// <summary>
        /// The name of the interchange program.
        /// </summary>
        [JsonProperty("programName")]
        public string ProgramName { get; set; } = default!;

        /// <summary>
        /// The number of transactions for this program.
        /// </summary>
        [JsonProperty("count")]
        public long Count { get; set; } = default!;

        /// <summary>
        /// The percentage rate for this program.
        /// </summary>
        [JsonProperty("percentageRate")]
        public decimal PercentageRate { get; set; } = default!;

        /// <summary>
        /// The per-item rate for this program.
        /// </summary>
        [JsonProperty("perItemRate")]
        public AmountDecimal PerItemRate { get; set; } = default!;

        /// <summary>
        /// The total fee amount for this program.
        /// </summary>
        [JsonProperty("total")]
        public AmountDecimal Total { get; set; } = default!;

        /// <summary>
        /// The total transfer volume for this program.
        /// </summary>
        [JsonProperty("transferVolume")]
        public AmountDecimal TransferVolume { get; set; } = default!;
    }
}