//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Utils;
    using Newtonsoft.Json;
    
    public class CardAcceptanceMethodsError
    {

        [JsonProperty("inPersonPercentage")]
        public string? InPersonPercentage { get; set; }

        [JsonProperty("mailOrPhonePercentage")]
        public string? MailOrPhonePercentage { get; set; }

        [JsonProperty("onlinePercentage")]
        public string? OnlinePercentage { get; set; }
    }
}