//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The results of the card update request.
    /// </summary>
    public enum CardUpdateReason
    {
        [JsonProperty("unspecified")]
        Unspecified,
        [JsonProperty("account-closed")]
        AccountClosed,
        [JsonProperty("contact-cardholder")]
        ContactCardholder,
        [JsonProperty("expiration-update")]
        ExpirationUpdate,
        [JsonProperty("no-change")]
        NoChange,
        [JsonProperty("no-match")]
        NoMatch,
        [JsonProperty("number-update")]
        NumberUpdate,
    }

    public static class CardUpdateReasonExtension
    {
        public static string Value(this CardUpdateReason value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CardUpdateReason ToEnum(this string value)
        {
            foreach(var field in typeof(CardUpdateReason).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CardUpdateReason)
                    {
                        return (CardUpdateReason)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CardUpdateReason");
        }
    }

}