//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    
    public class CreateEvidenceText
    {

        /// <summary>
        /// The text to associate with the dispute as evidence.
        /// </summary>
        [JsonProperty("text")]
        public string Text { get; set; } = default!;

        [JsonProperty("evidenceType")]
        public EvidenceType EvidenceType { get; set; } = default!;
    }
}