//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class CreateProductOption
    {

        /// <summary>
        /// The display name of a product option.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// A detailed description of the option.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// - Must be valid UTF-8 text<br/>
        /// - Supports Markdown for formatting<br/>
        /// - HTML is not permitted and will be rejected
        /// </remarks>
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The adjustment applied to a product&apos;s base price by this option. Can be negative, positive, or zero.
        /// </summary>
        [JsonProperty("priceModifier")]
        public AmountDecimal? PriceModifier { get; set; }

        /// <summary>
        /// Assign previously uploaded images to a product or option.
        /// </summary>
        [JsonProperty("images")]
        public List<AssignProductImage>? Images { get; set; }
    }
}