//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class CreateAccount
    {

        [JsonProperty("accountType")]
        public CreateAccountType AccountType { get; set; } = default!;

        [JsonProperty("profile")]
        public CreateProfile Profile { get; set; } = default!;

        /// <summary>
        /// Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; }

        [JsonProperty("termsOfService", NullValueHandling = NullValueHandling.Include)]
        public CreateAccountTermsOfService? TermsOfService { get; set; }

        /// <summary>
        /// Optional alias from a foreign/external system which can be used to reference this resource.
        /// </summary>
        [JsonProperty("foreignID")]
        public string? ForeignID { get; set; }

        /// <summary>
        /// User-provided information that can be displayed on credit card transactions for customers to use when<br/>
        /// 
        /// <remarks>
        /// contacting a customer support team. This data is only allowed on a business account.
        /// </remarks>
        /// </summary>
        [JsonProperty("customerSupport")]
        public CustomerSupport? CustomerSupport { get; set; }

        /// <summary>
        /// User provided settings to manage an account.
        /// </summary>
        [JsonProperty("settings")]
        public Settings? Settings { get; set; }

        [JsonProperty("capabilities")]
        public List<CapabilityID>? Capabilities { get; set; }

        /// <summary>
        /// The operating mode for an account.
        /// </summary>
        [JsonProperty("mode")]
        public Mode? Mode { get; set; }
    }
}