//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class Document
    {

        [JsonProperty("documentID")]
        public string DocumentID { get; set; } = default!;

        /// <summary>
        /// Types of documents that can be uploaded.
        /// </summary>
        [JsonProperty("type")]
        public DocumentType Type { get; set; } = default!;

        /// <summary>
        /// The document&apos;s MIME type.
        /// </summary>
        [JsonProperty("contentType")]
        public string ContentType { get; set; } = default!;

        /// <summary>
        /// Optional array of errors encountered during automated parsing.
        /// </summary>
        [JsonProperty("parseErrors")]
        public List<string>? ParseErrors { get; set; }

        [JsonProperty("uploadedAt")]
        public DateTime UploadedAt { get; set; } = default!;
    }
}