//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// The minimum spending amount that must be met in the billing period. If actual usage is below the minimum amount, account is charged the difference.
    /// </summary>
    public class MinimumCommitment
    {

        /// <summary>
        /// A 3-letter ISO 4217 currency code.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; } = default!;

        /// <summary>
        /// A decimal-formatted numerical string that represents up to 9 decimal place precision. <br/>
        /// 
        /// <remarks>
        /// <br/>
        /// For example, $12.987654321 is &apos;12.987654321&apos;.
        /// </remarks>
        /// </summary>
        [JsonProperty("valueDecimal")]
        public string ValueDecimal { get; set; } = default!;
    }
}