//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// A detailed breakdown of platform fees.
    /// </summary>
    public class PlatformFees
    {

        /// <summary>
        /// Fees associated with wallet services.
        /// </summary>
        [JsonProperty("walletFee")]
        public AmountDecimal WalletFee { get; set; } = default!;

        /// <summary>
        /// Fees for PCI compliance.
        /// </summary>
        [JsonProperty("merchantPCIFee")]
        public AmountDecimal MerchantPCIFee { get; set; } = default!;

        /// <summary>
        /// Total platform fees.
        /// </summary>
        [JsonProperty("total")]
        public AmountDecimal Total { get; set; } = default!;
    }
}