//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// If the business is a financial institution, this field describes its primary regulator.
    /// </summary>
    public enum PrimaryRegulator
    {
        [JsonProperty("OCC")]
        Occ,
        [JsonProperty("FDIC")]
        Fdic,
        [JsonProperty("NCUA")]
        Ncua,
        [JsonProperty("FRB")]
        Frb,
        [JsonProperty("state-cu-regulator")]
        StateCuRegulator,
    }

    public static class PrimaryRegulatorExtension
    {
        public static string Value(this PrimaryRegulator value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PrimaryRegulator ToEnum(this string value)
        {
            foreach(var field in typeof(PrimaryRegulator).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PrimaryRegulator)
                    {
                        return (PrimaryRegulator)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PrimaryRegulator");
        }
    }

}