//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    
    public class RTPInstitution
    {

        /// <summary>
        /// Name of the financial institution.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("routingNumber")]
        public string RoutingNumber { get; set; } = default!;

        [JsonProperty("services")]
        public RTPServices Services { get; set; } = default!;
    }
}