//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Defines the attributes of a transfer.
    /// </summary>
    public class RunTransfer
    {

        [JsonProperty("amount")]
        public Amount Amount { get; set; } = default!;

        [JsonProperty("destination")]
        public SchedulePaymentMethod Destination { get; set; } = default!;

        [JsonProperty("partnerAccountID")]
        public string PartnerAccountID { get; set; } = default!;

        [JsonProperty("source")]
        public SchedulePaymentMethod Source { get; set; } = default!;

        /// <summary>
        /// Simple description to place on the transfer.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; } = default!;
    }
}