//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    
    public class SchedulePaymentMethod
    {

        [JsonProperty("paymentMethodID")]
        public string PaymentMethodID { get; set; } = default!;

        [JsonProperty("achDetails")]
        public AchDetails? AchDetails { get; set; }

        [JsonProperty("cardDetails")]
        public CardDetails? CardDetails { get; set; }
    }
}