//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// A billing statement for a Moov account.
    /// </summary>
    public class Statement
    {

        /// <summary>
        /// The unique identifier for the statement.
        /// </summary>
        [JsonProperty("statementID")]
        public string StatementID { get; set; } = default!;

        /// <summary>
        /// The name of the statement.
        /// </summary>
        [JsonProperty("statementName")]
        public string StatementName { get; set; } = default!;

        /// <summary>
        /// The name of the statement file.
        /// </summary>
        [JsonProperty("fileName")]
        public string FileName { get; set; } = default!;

        /// <summary>
        /// The size of the statement file in bytes.
        /// </summary>
        [JsonProperty("fileSize")]
        public long FileSize { get; set; } = default!;

        /// <summary>
        /// The start date and time of the billing period.
        /// </summary>
        [JsonProperty("billingPeriodStartDateTime")]
        public DateTime BillingPeriodStartDateTime { get; set; } = default!;

        /// <summary>
        /// The end date and time of the billing period.
        /// </summary>
        [JsonProperty("billingPeriodEndDateTime")]
        public DateTime BillingPeriodEndDateTime { get; set; } = default!;

        /// <summary>
        /// List of subscription IDs associated with this statement.
        /// </summary>
        [JsonProperty("subscriptionIDs")]
        public List<string> SubscriptionIDs { get; set; } = default!;

        /// <summary>
        /// A summary of all fees included in this statement.
        /// </summary>
        [JsonProperty("summary")]
        public BillingSummary Summary { get; set; } = default!;

        /// <summary>
        /// A detailed breakdown of card acquiring fees.
        /// </summary>
        [JsonProperty("cardAcquiringFees")]
        public CardAcquiringFees? CardAcquiringFees { get; set; }

        /// <summary>
        /// A detailed breakdown of ACH fees.
        /// </summary>
        [JsonProperty("achFees")]
        public ACHFees? AchFees { get; set; }

        /// <summary>
        /// A detailed breakdown of instant payment fees.
        /// </summary>
        [JsonProperty("instantPaymentFees")]
        public InstantPaymentFees? InstantPaymentFees { get; set; }

        /// <summary>
        /// A detailed breakdown of platform fees.
        /// </summary>
        [JsonProperty("platformFees")]
        public PlatformFees? PlatformFees { get; set; }

        /// <summary>
        /// A detailed breakdown of other card-related fees.
        /// </summary>
        [JsonProperty("otherCardFees")]
        public OtherCardFees? OtherCardFees { get; set; }

        /// <summary>
        /// The date and time the statement was created.
        /// </summary>
        [JsonProperty("createdOn")]
        public DateTime CreatedOn { get; set; } = default!;

        /// <summary>
        /// The date and time the statement was last updated.
        /// </summary>
        [JsonProperty("updatedOn")]
        public DateTime UpdatedOn { get; set; } = default!;
    }
}