//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An EIN (employer identification number) for the business. For sole proprietors, an SSN can be used as the EIN.
    /// </summary>
    public class TaxID
    {

        [JsonProperty("ein")]
        public TaxIDEin Ein { get; set; } = default!;
    }
}