//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Describes a terminal application version.
    /// </summary>
    public class TerminalApplicationVersion
    {

        /// <summary>
        /// The app version of the terminal application (version code for Android terminal application).
        /// </summary>
        [JsonProperty("version")]
        public string Version { get; set; } = default!;
    }
}