//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Models.Components
{
    using Moov.Models.Components;
    using Moov.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// A transaction that funds or deducts from the wallet.
    /// </summary>
    public class WalletTransaction
    {

        [JsonProperty("walletID")]
        public string WalletID { get; set; } = default!;

        [JsonProperty("transactionID")]
        public string TransactionID { get; set; } = default!;

        [JsonProperty("transactionType")]
        public WalletTransactionType TransactionType { get; set; } = default!;

        [JsonProperty("sourceType")]
        public WalletTransactionSourceType SourceType { get; set; } = default!;

        /// <summary>
        /// The ID of the Moov object to which this transaction is related.
        /// </summary>
        [JsonProperty("sourceID")]
        public string SourceID { get; set; } = default!;

        [JsonProperty("status")]
        public WalletTransactionStatus Status { get; set; } = default!;

        /// <summary>
        /// Detailed description of the transaction.
        /// </summary>
        [JsonProperty("memo")]
        public string Memo { get; set; } = default!;

        [JsonProperty("createdOn")]
        public DateTime CreatedOn { get; set; } = default!;

        [JsonProperty("completedOn")]
        public DateTime? CompletedOn { get; set; }

        /// <summary>
        /// A 3-letter ISO 4217 currency code.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; } = default!;

        /// <summary>
        /// The total transaction amount. The amount is in the smallest unit of the specified currency. In USD this is cents, for example, $12.04 is 1204 and $0.99 is 99.
        /// </summary>
        [JsonProperty("grossAmount")]
        public long GrossAmount { get; set; } = default!;

        /// <summary>
        /// The total transaction amount. Same as `grossAmount`, but a decimal-formatted numerical string that represents up to 9 decimal place precision. In USD for example, 12.987654321 is $12.987654321 and 0.9987634521 is $0.9987634521.
        /// </summary>
        [JsonProperty("grossAmountDecimal")]
        public string GrossAmountDecimal { get; set; } = default!;

        /// <summary>
        /// Total fees paid for the transaction. The value is in the smallest unit of the specified currency. In USD this is cents, for example, $12.04 is 1204 and $0.99 is 99.
        /// </summary>
        [JsonProperty("fee")]
        public long Fee { get; set; } = default!;

        /// <summary>
        /// The IDs of the fees paid for the transaction.
        /// </summary>
        [JsonProperty("feeIDs")]
        public List<string>? FeeIDs { get; set; }

        /// <summary>
        /// Total fees paid for the transaction. Same as `fee`, but a decimal-formatted numerical string that represents up to 9 decimal place precision. In USD for example, 12.987654321 is $12.987654321 and 0.9987634521 is $0.9987634521.
        /// </summary>
        [JsonProperty("feeDecimal")]
        public string FeeDecimal { get; set; } = default!;

        /// <summary>
        /// Net amount is the gross amount less fees paid, and the amount that affects the wallet&apos;s balance. The amount is in the smallest unit of the specified currency. In USD this is cents, for example, $12.04 is 1204 and $0.99 is 99.
        /// </summary>
        [JsonProperty("netAmount")]
        public long NetAmount { get; set; } = default!;

        /// <summary>
        /// Net amount is the gross amount less fees paid, and the amount that affects the wallet&apos;s balance. Same as `netAmount`, but a decimal-formatted numerical string that represents up to 9 decimal place precision. In USD for example, 12.987654321 is $12.987654321 and 0.9987634521 is $0.9987634521.
        /// </summary>
        [JsonProperty("netAmountDecimal")]
        public string NetAmountDecimal { get; set; } = default!;

        /// <summary>
        /// The wallet&apos;s total available balance after recording a completed transaction. The value is in the smallest unit of the specified currency. In USD this is cents, for example, $12.04 is 1204 and $0.99 is 99.
        /// </summary>
        [JsonProperty("availableBalance")]
        public long? AvailableBalance { get; set; }

        /// <summary>
        /// The wallet&apos;s total available balance after recording a completed transaction. Same as `availableBalance`, but a decimal-formatted numerical string that represents up to 9 decimal place precision. In USD for example, 12.987654321 is $12.987654321 and 0.9987634521 is $0.9987634521.
        /// </summary>
        [JsonProperty("availableBalanceDecimal")]
        public string? AvailableBalanceDecimal { get; set; }

        /// <summary>
        /// ID of the sweep this transaction accrued in.
        /// </summary>
        [JsonProperty("sweepID")]
        public string? SweepID { get; set; }
    }
}