//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Requests
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;

    public class GetCapabilityRequest
    {
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountID")]
        public string AccountID { get; set; } = default!;

        /// <summary>
        /// Moov account capabilities.<br/>
        /// <br/>
        /// **Deprecated capabilities**<br/>
        /// <br/>
        /// The `send-funds`, `collect-funds`, and `wallet` capability IDs are deprecated. Request granular capabilities instead (for example, `send-funds.ach`, `collect-funds.card-payments`, or `wallet.balance`). Deprecated values will be removed in a future API version.<br/>
        /// <br/>
        /// Read our <a href="https://docs.moov.io/guides/accounts/capabilities/reference/">capabilities reference</a> to choose the right capabilities for your integration.<br/>
        /// <br/>
        /// The `production-app`, `platform.production-app`, and / or `platform.wallet-transfers` capabilities might appear in the list for your Partner account. These are read-only capabilities that Moov requests. These capabilities remain active with your account and require no additional action.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=capabilityID")]
        public CapabilityID CapabilityID { get; set; } = default!;
    }
}