//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Requests
{
    using Moov.Sdk.Utils;

    public class GetScheduledOccurrenceRequest
    {
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountID")]
        public string AccountID { get; set; } = default!;

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=scheduleID")]
        public string ScheduleID { get; set; } = default!;

        /// <summary>
        /// Allows the specification of additional filters beyond the string.<br/>
        /// <br/>
        ///   Specifying a string returns the exact occurrence.<br/>
        ///   Specifying a RFC 3339 timestamp returns the latest occurrence at or before that timestamp.<br/>
        ///   Specifying `latest` returns the latest occurrence at or before now.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=occurrenceFilter")]
        public string OccurrenceFilter { get; set; } = default!;
    }
}