//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Requests
{
    using Moov.Sdk.Utils;

    public class GetTermsOfServiceTokenRequest
    {
        /// <summary>
        /// Indicates the domain from which the request originated. Required if referer header is not present.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=origin")]
        public string? Origin { get; set; }

        /// <summary>
        /// Specifies the URL of the resource from which the request originated. Required if origin header is not present.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=referer")]
        public string? Referer { get; set; }
    }
}