//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Requests
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;

    public class UpdateWalletRequest
    {
        /// <summary>
        /// Identifier for the wallet.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=walletID")]
        public string WalletID { get; set; } = default!;

        /// <summary>
        /// The Moov account ID the wallet belongs to.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountID")]
        public string AccountID { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public PatchWallet Body { get; set; } = default!;
    }
}