//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Requests
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;

    public class UpdateInvoiceRequest
    {
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountID")]
        public string AccountID { get; set; } = default!;

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=invoiceID")]
        public string InvoiceID { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public UpdateInvoice Body { get; set; } = default!;
    }
}