//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// A detailed breakdown of adjustment (correction) fees by fee name.
    /// </summary>
    public class AdjustmentFees
    {
        /// <summary>
        /// Adjustment fees grouped by fee name.
        /// </summary>
        [JsonProperty("items")]
        public List<BillingAdjustment> Items { get; set; } = default!;

        /// <summary>
        /// Total adjustment fees.
        /// </summary>
        [JsonProperty("total")]
        public BillingCountAndAmount Total { get; set; } = default!;
    }
}