//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    
    public class AuthToken
    {

        /// <summary>
        /// An <a href="https://www.rfc-editor.org/rfc/rfc6750#section-6.1">RFC 6750</a> token type.
        /// </summary>
        [JsonProperty("token_type")]
        public TokenType TokenType { get; set; } = default!;

        /// <summary>
        /// A value passed to the authorization server to gain access to the system.
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken { get; set; } = default!;

        /// <summary>
        /// A value passed to the authorization server to obtain a new access token.
        /// </summary>
        [JsonProperty("refresh_token")]
        public string RefreshToken { get; set; } = default!;

        /// <summary>
        /// Unix timestamp indicating when this token expires.
        /// </summary>
        [JsonProperty("expires_in")]
        public int ExpiresIn { get; set; } = default!;

        /// <summary>
        /// A space-delimited list of <a href="https://docs.moov.io/api/authentication/scopes/">scopes</a> that are allowed.
        /// </summary>
        [JsonProperty("scope")]
        public string Scope { get; set; } = default!;
    }
}