//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Card-specific details about the transaction.
    /// </summary>
    public class CardTransactionDetails
    {
        /// <summary>
        /// Status of a transaction within the card payment lifecycle.
        /// </summary>
        [JsonProperty("status")]
        public CardTransactionStatus? Status { get; set; }

        [JsonProperty("failureCode")]
        public CardTransactionFailureCode? FailureCode { get; set; }

        /// <summary>
        /// An optional override of the default card statement descriptor for a transfer. Accounts must be enabled by Moov to set this field.
        /// </summary>
        [JsonProperty("dynamicDescriptor")]
        public string? DynamicDescriptor { get; set; }

        /// <summary>
        /// The scheduled date and time for the transfer to be delivered. This field is only valid for push-to-card transfers. Must be between 24 and 48 hours in the future in production. In sandbox mode, any future time up to 48 hours is accepted so integrations can test deferred delivery using the sandbox test cards with relaxed wait times.
        /// </summary>
        [JsonProperty("scheduledDeliveryOn")]
        public DateTime? ScheduledDeliveryOn { get; set; }

        /// <summary>
        /// Specifies the nature and initiator of a transaction. <br/>
        /// <br/>
        /// Crucial for recurring and merchant-initiated transactions as per card scheme rules. <br/>
        /// Omit for customer-initiated e-commerce transactions.
        /// </summary>
        [JsonProperty("transactionSource")]
        public TransactionSource? TransactionSource { get; set; }

        [JsonProperty("initiatedOn")]
        public DateTime? InitiatedOn { get; set; }

        [JsonProperty("confirmedOn")]
        public DateTime? ConfirmedOn { get; set; }

        [JsonProperty("settledOn")]
        public DateTime? SettledOn { get; set; }

        [JsonProperty("failedOn")]
        public DateTime? FailedOn { get; set; }

        [JsonProperty("canceledOn")]
        public DateTime? CanceledOn { get; set; }

        [JsonProperty("completedOn")]
        public DateTime? CompletedOn { get; set; }

        [JsonProperty("deferredOn")]
        public DateTime? DeferredOn { get; set; }

        /// <summary>
        /// The program assigned by the card network that determines the interchange rate for the transfer.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("interchangeQualification")]
        public string? InterchangeQualification { get; set; }

        /// <summary>
        /// The program assigned by the card network that determines the interchange rate for the transfer.
        /// </summary>
        [JsonProperty("feeProgram")]
        public string? FeeProgram { get; set; }

        /// <summary>
        /// An alphanumeric code generated by the card network to demonstrate approval for the transaction.
        /// </summary>
        [JsonProperty("authorizationCode")]
        public string? AuthorizationCode { get; set; }
    }
}