//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Describes the distribution of card transactions by payment method.
    /// </summary>
    public class CardAcceptanceMethods
    {

        /// <summary>
        /// Percentage of card transactions that are in-person payments. Minimum value is 0, maximum is 100.
        /// </summary>
        [JsonProperty("inPersonPercentage")]
        public int? InPersonPercentage { get; set; }

        /// <summary>
        /// Percentage of card transactions that are mail or phone payments. Minimum value is 0, maximum is 100.
        /// </summary>
        [JsonProperty("mailOrPhonePercentage")]
        public int? MailOrPhonePercentage { get; set; }

        /// <summary>
        /// Percentage of card transactions that are online payments. Minimum value is 0, maximum is 100.
        /// </summary>
        [JsonProperty("onlinePercentage")]
        public int? OnlinePercentage { get; set; }
    }
}