//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public class CreatedTransfer
    {
        [JsonProperty("transferID")]
        public string TransferID { get; set; } = default!;

        /// <summary>
        /// The rail and direction used to move funds for a transfer.
        /// </summary>
        [JsonProperty("transferType")]
        public TransferType TransferType { get; set; } = default!;

        [JsonProperty("createdOn")]
        public DateTime CreatedOn { get; set; } = default!;

        [JsonProperty("source")]
        public TransferSource? Source { get; set; }

        [JsonProperty("destination")]
        public TransferDestination? Destination { get; set; }

        [JsonProperty("completedOn")]
        public DateTime? CompletedOn { get; set; }

        /// <summary>
        /// Status of a transfer.
        /// </summary>
        [JsonProperty("status")]
        public TransferStatus? Status { get; set; }

        /// <summary>
        /// Reason for a transfer's failure.
        /// </summary>
        [JsonProperty("failureReason")]
        public TransferFailureReason? FailureReason { get; set; }

        /// <summary>
        /// Amount associated with this transfer.<br/>
        /// In v2026.10 and later, an auth-capture `card-payment` transfer reports the approved authorization amount until a final capture is created.<br/>
        /// For these transfers, when a final capture is created, this is updated to the cumulative captured amount.<br/>
        /// For other transfer types, this is the transfer amount.
        /// </summary>
        [JsonProperty("amount")]
        public AmountDecimal? Amount { get; set; }

        /// <summary>
        /// An optional description of the transfer that is used on receipts and for your own internal use.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; }

        /// <summary>
        /// Total or markup fee.
        /// </summary>
        [JsonProperty("facilitatorFee")]
        public FacilitatorFee? FacilitatorFee { get; set; }

        /// <summary>
        /// Fees charged to your platform account for transfers.
        /// </summary>
        [JsonProperty("moovFee")]
        public AmountDecimal? MoovFee { get; set; }

        /// <summary>
        /// Processing and pass-through costs that add up to the moovFee.
        /// </summary>
        [JsonProperty("moovFeeDetails")]
        public MoovFeeDetails? MoovFeeDetails { get; set; }

        [JsonProperty("groupID")]
        public string? GroupID { get; set; }

        [JsonProperty("refundedAmount")]
        public AmountDecimal? RefundedAmount { get; set; }

        [JsonProperty("disputedAmount")]
        public AmountDecimal? DisputedAmount { get; set; }

        [JsonProperty("sweepID")]
        public string? SweepID { get; set; }

        [JsonProperty("scheduleID")]
        public string? ScheduleID { get; set; }

        [JsonProperty("occurrenceID")]
        public string? OccurrenceID { get; set; }

        [JsonProperty("paymentLinkCode")]
        public string? PaymentLinkCode { get; set; }

        /// <summary>
        /// Optional alias from a foreign/external system which can be used to reference this resource.
        /// </summary>
        [JsonProperty("foreignID")]
        public string? ForeignID { get; set; }

        /// <summary>
        /// An optional collection of line items for a transfer.<br/>
        /// When line items are provided, their total plus tax must equal the transfer amount.
        /// </summary>
        [JsonProperty("lineItems")]
        public TransferLineItems? LineItems { get; set; }

        [JsonProperty("amountDetails")]
        public TransferAmountDetails? AmountDetails { get; set; }

        /// <summary>
        /// Authorization amounts.<br/>
        /// This field is present only for an auth-capture `card-payment` transfer.
        /// </summary>
        [JsonProperty("authorization")]
        public TransferAuthorization? Authorization { get; set; }

        [JsonProperty("options")]
        public TransferRailOptions Options { get; set; } = default!;

        [JsonProperty("processingDetails")]
        public TransferProcessingDetails ProcessingDetails { get; set; } = default!;
    }
}