//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Types of documents that can be uploaded.
    /// </summary>
    public enum DocumentType
    {
        [JsonProperty("driversLicense")]
        DriversLicense,
        [JsonProperty("passport")]
        Passport,
        [JsonProperty("utilityBill")]
        UtilityBill,
        [JsonProperty("bankStatement")]
        BankStatement,
    }

    public static class DocumentTypeExtension
    {
        public static string Value(this DocumentType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DocumentType ToEnum(this string value)
        {
            foreach(var field in typeof(DocumentType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DocumentType)
                    {
                        return (DocumentType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DocumentType");
        }
    }

}