//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Describes a file linked to a Moov account.
    /// </summary>
    public class FileDetails
    {

        [JsonProperty("fileID")]
        public string FileID { get; set; } = default!;

        [JsonProperty("fileName")]
        public string FileName { get; set; } = default!;

        [JsonProperty("accountID")]
        public string AccountID { get; set; } = default!;

        /// <summary>
        /// The file&apos;s purpose.
        /// </summary>
        [JsonProperty("filePurpose")]
        public FilePurpose FilePurpose { get; set; } = default!;

        /// <summary>
        /// The file&apos;s status.
        /// </summary>
        [JsonProperty("fileStatus")]
        public FileStatus FileStatus { get; set; } = default!;

        [JsonProperty("metadata")]
        public string Metadata { get; set; } = default!;

        [JsonProperty("decisionReason")]
        public string? DecisionReason { get; set; }

        [JsonProperty("fileSizeBytes")]
        public long FileSizeBytes { get; set; } = default!;

        [JsonProperty("createdOn")]
        public DateTime CreatedOn { get; set; } = default!;

        [JsonProperty("updatedOn")]
        public DateTime UpdatedOn { get; set; } = default!;
    }
}