//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Additional metadata to be stored with the file.
    /// </summary>
    public class FileUploadMetadata
    {
        /// <summary>
        /// The representative ID that the file is for. Required when filePurpose is `representativeVerification`.
        /// </summary>
        [JsonProperty("representative_id")]
        public string? RepresentativeId { get; set; }

        /// <summary>
        /// Comments or notes about the file.
        /// </summary>
        [JsonProperty("comment")]
        public string? Comment { get; set; }
    }
}