//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Contains the encrypted payment token as returned from Google Pay.<br/>
    /// <br/>
    ///   Refer to <a href="https://developers.google.com/pay/api/web/guides/resources/payment-data-cryptography#payment-method-token-structure">Google's documentation</a>
    ///   for more information.
    /// </summary>
    public class GooglePayToken
    {
        /// <summary>
        /// The version of the encryption/signing protocol. Must be `ECv2`.
        /// </summary>
        [JsonProperty("protocolVersion")]
        public string ProtocolVersion { get; set; } = default!;

        /// <summary>
        /// A Base64-encoded signature of the `signedMessage`.
        /// </summary>
        [JsonProperty("signature")]
        public string Signature { get; set; } = default!;

        /// <summary>
        /// Contains the intermediate signing key for verification.
        /// </summary>
        [JsonProperty("intermediateSigningKey")]
        public GooglePayIntermediateSigningKey IntermediateSigningKey { get; set; } = default!;

        /// <summary>
        /// A JSON-encoded serialized string containing the encrypted payment data.
        /// </summary>
        [JsonProperty("signedMessage")]
        public string SignedMessage { get; set; } = default!;
    }
}