//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Contains the intermediate signing key for verification.
    /// </summary>
    public class GooglePayIntermediateSigningKey
    {
        /// <summary>
        /// A JSON-encoded serialized string containing the signing key data.
        /// </summary>
        [JsonProperty("signedKey")]
        public string SignedKey { get; set; } = default!;

        /// <summary>
        /// Base64-encoded signatures of the `signedKey`.
        /// </summary>
        [JsonProperty("signatures")]
        public List<string> Signatures { get; set; } = default!;
    }
}