//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// A detailed breakdown of instant payment fees.
    /// </summary>
    public class InstantPaymentFees
    {
        /// <summary>
        /// Fees for RTP credit transactions.
        /// </summary>
        [JsonProperty("rtpCreditTransaction")]
        public BillingCountAndAmount RtpCreditTransaction { get; set; } = default!;

        /// <summary>
        /// Fees for RTP declines.
        /// </summary>
        [JsonProperty("rtpDecline")]
        public BillingCountAndAmount? RtpDecline { get; set; }

        /// <summary>
        /// Fees for push-to-card transactions.
        /// </summary>
        [JsonProperty("pushToCardTransaction")]
        public BillingCountAndAmount PushToCardTransaction { get; set; } = default!;

        /// <summary>
        /// Fees for push-to-card declines.
        /// </summary>
        [JsonProperty("pushToCardDecline")]
        public BillingCountAndAmount? PushToCardDecline { get; set; }

        /// <summary>
        /// Fees for pull-from-card transactions.
        /// </summary>
        [JsonProperty("pullFromCardTransaction")]
        public BillingCountAndAmount PullFromCardTransaction { get; set; } = default!;

        /// <summary>
        /// Fees for pull-from-card declines.
        /// </summary>
        [JsonProperty("pullFromCardDecline")]
        public BillingCountAndAmount? PullFromCardDecline { get; set; }

        /// <summary>
        /// Fees for pull-from-card refunds.
        /// </summary>
        [JsonProperty("pullFromCardRefund")]
        public BillingCountAndAmount? PullFromCardRefund { get; set; }

        /// <summary>
        /// Fees for instant payment verifications.
        /// </summary>
        [JsonProperty("instantVerification")]
        public BillingCountAndAmount InstantVerification { get; set; } = default!;

        /// <summary>
        /// Total instant payment fees.
        /// </summary>
        [JsonProperty("total")]
        public BillingCountAndAmount Total { get; set; } = default!;
    }
}