//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    ///   Provides information about the underlying card.<br/>
    /// 
    /// <remarks>
    /// <br/>
    ///   Refer to <a href="https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymenttoken/1916113-paymentmethod">Apple&apos;s documentation</a> <br/>
    ///   for more information.
    /// </remarks>
    /// </summary>
    public class LinkApplePaymentMethod
    {

        /// <summary>
        /// A display-friendly discription of the card.
        /// </summary>
        [JsonProperty("displayName")]
        public string DisplayName { get; set; } = default!;

        /// <summary>
        /// The card&apos;s payment network.
        /// </summary>
        [JsonProperty("network")]
        public string Network { get; set; } = default!;

        /// <summary>
        /// The type of card.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; } = default!;
    }
}