//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Restricts card usage to specific merchants, independent of merchant category.
    /// </summary>
    public class MerchantRestrictions
    {
        /// <summary>
        /// Whether the listed items should be allowed (`allow`) or blocked (`block`).
        /// </summary>
        [JsonProperty("mode")]
        public IssuingControlsRestrictionMode Mode { get; set; } = default!;

        /// <summary>
        /// The merchants to allow or block.
        /// </summary>
        [JsonProperty("merchants")]
        public List<MerchantEntry> Merchants { get; set; } = default!;
    }
}