//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    
    public class MoovWalletPaymentMethod
    {

        /// <summary>
        /// ID of the payment method.
        /// </summary>
        [JsonProperty("paymentMethodID")]
        public string PaymentMethodID { get; set; } = default!;

        [JsonProperty("paymentMethodType")]
        public MoovWalletPaymentMethodPaymentMethodType PaymentMethodType { get; set; } = default!;

        [JsonProperty("wallet")]
        public PaymentMethodsWallet Wallet { get; set; } = default!;
    }
}