//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class PatchTransfer
    {
        /// <summary>
        /// Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; } = null;

        /// <summary>
        /// Optional alias from a foreign/external system which can be used to reference this resource.
        /// </summary>
        [JsonProperty("foreignID")]
        public string? ForeignID { get; set; } = null;
    }
}