//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class PaymentLinkPayoutDetailsUpdate
    {
        /// <summary>
        /// A list of payment methods that should be supported for this payment link.
        /// </summary>
        [JsonProperty("allowedMethods")]
        public List<DisbursementPaymentMethodType>? AllowedMethods { get; set; }

        /// <summary>
        /// Specify the intended recipient of the payout.<br/>
        /// Either `email` or `phone` must be specified, but not both.<br/>
        /// <br/>
        /// This information will be used to authenticate the end user when they follow the payment link.
        /// </summary>
        [JsonProperty("recipient")]
        public PayoutRecipient? Recipient { get; set; }

        /// <summary>
        /// Optional free-form metadata for the transfer.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; }

        /// <summary>
        /// Delivery options for push-to-card payouts. Only applies when `allowedMethods` includes `push-to-card`.<br/>
        /// <br/>
        /// The `deferred` speed and `deferredBy` apply to `push-to-card` only. Other push methods<br/>
        /// (`push-to-apple-pay`, `push-to-google-pay`) are always delivered instantly regardless of these options.
        /// </summary>
        [JsonProperty("pushOptions")]
        public PushOptionsUpdate? PushOptions { get; set; }

        /// <summary>
        /// Indicates which party bears the fee, keyed by disbursement payment method (`DisbursementPaymentMethodType`).<br/>
        /// <br/>
        /// Sparse — include only the methods you want to attribute. Any method left unset defaults to `source`.
        /// </summary>
        [JsonProperty("feePaidBy")]
        public Dictionary<string, FeePaidBy>? FeePaidBy { get; set; }
    }
}