//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// This is used by Moov.js with a Plaid reseller relationship. The details of a Plaid link integration for a linked funding source.<br/>
    /// <br/>
    /// You can simulate linking bank accounts with Plaid in test mode. See our <a href="https://docs.moov.io/guides/get-started/test-mode/#plaid">test mode</a>
    /// guide for more information.<br/>
    /// <br/>
    /// Plaid's `sandbox` environment - (requires Plaid reseller setup with Moov). When linking a bank account to a `sandbox` account using a Plaid <br/>
    /// public token it will utilize Plaid's sandbox environment. The Plaid public token provided must be generated from Plaid's sandbox environment. <br/>
    /// Please see <a href="https://plaid.com/docs/api/sandbox/#sandboxpublic_tokencreate" target="_blank">Plaid's sandbox documentation</a> for more <br/>
    /// details.
    /// </summary>
    public class PlaidLinkIntegration
    {
        [JsonProperty("publicToken")]
        public string PublicToken { get; set; } = default!;
    }
}