//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The unique ID of what the requirement is asking to be filled out.
    /// </summary>
    public enum RequirementID
    {
        [JsonProperty("account.tos-acceptance")]
        AccountTosAcceptance,
        [JsonProperty("individual.mobile")]
        IndividualMobile,
        [JsonProperty("individual.email")]
        IndividualEmail,
        [JsonProperty("individual.email-or-mobile")]
        IndividualEmailOrMobile,
        [JsonProperty("individual.firstname")]
        IndividualFirstname,
        [JsonProperty("individual.lastname")]
        IndividualLastname,
        [JsonProperty("individual.address")]
        IndividualAddress,
        [JsonProperty("individual.ssn-last4")]
        IndividualSsnLast4,
        [JsonProperty("individual.ssn")]
        IndividualSsn,
        [JsonProperty("individual.birthdate")]
        IndividualBirthdate,
        [JsonProperty("business.legalname")]
        BusinessLegalname,
        [JsonProperty("business.description-or-website")]
        BusinessDescriptionOrWebsite,
        [JsonProperty("business.entity-type")]
        BusinessEntityType,
        [JsonProperty("business.business-type")]
        BusinessBusinessType,
        [JsonProperty("business.dba")]
        BusinessDba,
        [JsonProperty("business.ein")]
        BusinessEin,
        [JsonProperty("business.address")]
        BusinessAddress,
        [JsonProperty("business.phone")]
        BusinessPhone,
        [JsonProperty("business.admins")]
        BusinessAdmins,
        [JsonProperty("business.controllers")]
        BusinessControllers,
        [JsonProperty("business.owners")]
        BusinessOwners,
        [JsonProperty("business.classification")]
        BusinessClassification,
        [JsonProperty("business.industry-code-mcc")]
        BusinessIndustryCodeMcc,
        [JsonProperty("business.industry")]
        BusinessIndustry,
        [JsonProperty("business.indicate-owners-provided")]
        BusinessIndicateOwnersProvided,
        [JsonProperty("business.average-transaction-size")]
        BusinessAverageTransactionSize,
        [JsonProperty("business.max-transaction-size")]
        BusinessMaxTransactionSize,
        [JsonProperty("business.average-monthly-transaction-volume")]
        BusinessAverageMonthlyTransactionVolume,
        [JsonProperty("business.volume-by-customer-type")]
        BusinessVolumeByCustomerType,
        [JsonProperty("business.card-volume-distribution")]
        BusinessCardVolumeDistribution,
        [JsonProperty("business.fulfillment")]
        BusinessFulfillment,
        [JsonProperty("business.description")]
        BusinessDescription,
        [JsonProperty("business.underwriting-documents-tier-one")]
        BusinessUnderwritingDocumentsTierOne,
        [JsonProperty("bank-accounts.name")]
        BankAccountsName,
        [JsonProperty("bank-accounts.routing-number")]
        BankAccountsRoutingNumber,
        [JsonProperty("bank-accounts.account-number")]
        BankAccountsAccountNumber,
        [JsonProperty("document.business.verification")]
        DocumentBusinessVerification,
        [JsonProperty("document.individual.tin")]
        DocumentIndividualTin,
        [JsonProperty("document.individual.verification")]
        DocumentIndividualVerification,
        [JsonProperty("document.representative.{rep-uuid}.tin")]
        DocumentRepresentativeRepUuidTin,
        [JsonProperty("document.representative.{rep-uuid}.verification")]
        DocumentRepresentativeRepUuidVerification,
        [JsonProperty("representative.{rep-uuid}.mobile")]
        RepresentativeRepUuidMobile,
        [JsonProperty("representative.{rep-uuid}.email")]
        RepresentativeRepUuidEmail,
        [JsonProperty("representative.{rep-uuid}.email-or-mobile")]
        RepresentativeRepUuidEmailOrMobile,
        [JsonProperty("representative.{rep-uuid}.firstname")]
        RepresentativeRepUuidFirstname,
        [JsonProperty("representative.{rep-uuid}.lastname")]
        RepresentativeRepUuidLastname,
        [JsonProperty("representative.{rep-uuid}.address")]
        RepresentativeRepUuidAddress,
        [JsonProperty("representative.{rep-uuid}.ssn-last4")]
        RepresentativeRepUuidSsnLast4,
        [JsonProperty("representative.{rep-uuid}.ssn")]
        RepresentativeRepUuidSsn,
        [JsonProperty("representative.{rep-uuid}.birthdate")]
        RepresentativeRepUuidBirthdate,
        [JsonProperty("representative.{rep-uuid}.job-title")]
        RepresentativeRepUuidJobTitle,
        [JsonProperty("representative.{rep-uuid}.is-controller")]
        RepresentativeRepUuidIsController,
        [JsonProperty("representative.{rep-uuid}.is-owner")]
        RepresentativeRepUuidIsOwner,
        [JsonProperty("representative.{rep-uuid}.ownership")]
        RepresentativeRepUuidOwnership,
        [JsonProperty("document.{doc-uuid}")]
        DocumentDocUuid,
    }

    public static class RequirementIDExtension
    {
        public static string Value(this RequirementID value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static RequirementID ToEnum(this string value)
        {
            foreach(var field in typeof(RequirementID).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is RequirementID)
                    {
                        return (RequirementID)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum RequirementID");
        }
    }
}