//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// DEPRECATED: use `InstantBankTransactionDetails` instead (v2026.04.00 or later). RTP specific details about the transaction.
    /// </summary>
    [Obsolete("This will be removed in a future release, please migrate away from it as soon as possible")]
    public class RTPTransactionDetails
    {
        /// <summary>
        /// Status of a transaction within the RTP lifecycle.
        /// </summary>
        [JsonProperty("status")]
        public RTPTransactionStatus? Status { get; set; }

        /// <summary>
        /// Response code returned by network on failure.
        /// </summary>
        [JsonProperty("networkResponseCode")]
        public string? NetworkResponseCode { get; set; }

        /// <summary>
        /// Status codes for RTP failures.
        /// </summary>
        [JsonProperty("failureCode")]
        public RTPFailureCode? FailureCode { get; set; }

        [JsonProperty("initiatedOn")]
        public DateTime? InitiatedOn { get; set; }

        [JsonProperty("completedOn")]
        public DateTime? CompletedOn { get; set; }

        [JsonProperty("failedOn")]
        public DateTime? FailedOn { get; set; }

        [JsonProperty("acceptedWithoutPostingOn")]
        public DateTime? AcceptedWithoutPostingOn { get; set; }
    }
}