//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    public class RunTransfer
    {
        [JsonProperty("amount")]
        public Amount Amount { get; set; } = default!;

        /// <summary>
        /// Optional sales tax amount. This amount is included in the total transfer amount.
        /// </summary>
        [JsonProperty("salesTaxAmount")]
        public Amount? SalesTaxAmount { get; set; }

        [JsonProperty("destination")]
        public SchedulePaymentMethod Destination { get; set; } = default!;

        [JsonProperty("partnerAccountID")]
        public string PartnerAccountID { get; set; } = default!;

        [JsonProperty("source")]
        public SchedulePaymentMethod Source { get; set; } = default!;

        /// <summary>
        /// Simple description to place on the transfer.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; } = default!;

        /// <summary>
        /// Line items for a scheduled transfer.
        /// </summary>
        [JsonProperty("lineItems")]
        public ScheduledTransferLineItems? LineItems { get; set; }
    }
}