//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    public class TransferDestination
    {
        [JsonProperty("paymentMethodID")]
        public string PaymentMethodID { get; set; } = default!;

        /// <summary>
        /// The payment method type that represents a payment rail and directionality.
        /// </summary>
        [JsonProperty("paymentMethodType")]
        public TransferPaymentMethodType PaymentMethodType { get; set; } = default!;

        [JsonProperty("account")]
        public TransferAccount Account { get; set; } = default!;

        /// <summary>
        /// A bank account as contained within a payment method.
        /// </summary>
        [JsonProperty("bankAccount")]
        public TransferPaymentMethodsBankAccount? BankAccount { get; set; }

        [JsonProperty("wallet")]
        public TransferPaymentMethodsWallet? Wallet { get; set; }

        /// <summary>
        /// A card as contained within a payment method.
        /// </summary>
        [JsonProperty("card")]
        public TransferPaymentMethodsCard? Card { get; set; }

        /// <summary>
        /// ACH specific details about the transaction.
        /// </summary>
        [JsonProperty("achDetails")]
        public ACHTransactionDetails? AchDetails { get; set; }

        /// <summary>
        /// Describes an Apple Pay token on a Moov account.
        /// </summary>
        [JsonProperty("applePay")]
        public ApplePayResponse? ApplePay { get; set; }

        /// <summary>
        /// Card-specific details about the transaction.
        /// </summary>
        [JsonProperty("cardDetails")]
        public CardTransactionDetails? CardDetails { get; set; }

        /// <summary>
        /// Instant-bank specific details about the transaction.
        /// </summary>
        [JsonProperty("instantBankDetails")]
        public InstantBankTransactionDetails? InstantBankDetails { get; set; }
    }
}