//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Details for a Transfer timeline event. A valid event contains exactly one detail object matching its event type.
    /// </summary>
    public class TransferEventDetails
    {
        [JsonProperty("transfer")]
        public TransferEventTransferDetails? Transfer { get; set; }

        [JsonProperty("authorization")]
        public TransferEventAuthorizationDetails? Authorization { get; set; }

        [JsonProperty("capture")]
        public TransferEventCaptureDetails? Capture { get; set; }

        [JsonProperty("refund")]
        public TransferEventRefundDetails? Refund { get; set; }

        [JsonProperty("cancellation")]
        public TransferEventCancellationDetails? Cancellation { get; set; }

        [JsonProperty("dispute")]
        public TransferEventDisputeDetails? Dispute { get; set; }

        [JsonProperty("achCredit")]
        public TransferEventACHDetails? AchCredit { get; set; }

        [JsonProperty("achDebit")]
        public TransferEventACHDetails? AchDebit { get; set; }

        [JsonProperty("instantBankCredit")]
        public TransferEventInstantBankCreditDetails? InstantBankCredit { get; set; }

        [JsonProperty("wireCredit")]
        public TransferEventWireCreditDetails? WireCredit { get; set; }

        [JsonProperty("cardPayment")]
        public TransferEventCardPaymentDetails? CardPayment { get; set; }

        [JsonProperty("pushToCard")]
        public TransferEventPushToCardDetails? PushToCard { get; set; }

        [JsonProperty("pullFromCard")]
        public TransferEventPullFromCardDetails? PullFromCard { get; set; }

        [JsonProperty("walletCredit")]
        public TransferEventWalletTransactionDetails? WalletCredit { get; set; }

        [JsonProperty("walletDebit")]
        public TransferEventWalletTransactionDetails? WalletDebit { get; set; }
    }
}