//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    
    public class UpdateEvidence
    {

        [JsonProperty("evidenceType")]
        public EvidenceType? EvidenceType { get; set; }

        /// <summary>
        /// If updating text evidence, the new text to associate with the dispute.
        /// </summary>
        [JsonProperty("text")]
        public string? Text { get; set; }
    }
}