//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    
    public class UpdateIssuedCard
    {

        /// <summary>
        /// The `state` represents the operational status of an issued card. A card can only approve incoming authorizations if it is in an active state.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// - `active`: The card is operational and approves authorizations. Generally becomes active shortly after card creation.<br/>
        /// - `inactive`: The card cannot approve authorizations. This is currently a temporary state assigned post-creation during the activation process.<br/>
        /// - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be closed by request or when it expires.<br/>
        /// - `pending-verification`: Awaiting additional authorized user verification before the card can be activated.
        /// </remarks>
        /// </summary>
        [JsonProperty("state")]
        public IssuedCardState? State { get; set; }

        [JsonProperty("memo")]
        public string? Memo { get; set; }

        /// <summary>
        /// Fields for identifying an authorized individual.
        /// </summary>
        [JsonProperty("authorizedUser")]
        public CreateAuthorizedUserUpdate? AuthorizedUser { get; set; }
    }
}