//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class UpdateIssuedCard
    {
        /// <summary>
        /// Updates the state of a Moov issued card.<br/>
        /// - `active`: Reactivates a frozen card so it can approve authorizations again.<br/>
        /// - `frozen`: Temporarily suspends the card so it cannot approve authorizations. A card can be moved between `frozen` and `active` at will until it is `closed`, which is a terminal state.<br/>
        /// - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be closed by request or when it expires.
        /// </summary>
        [JsonProperty("state")]
        public UpdateIssuedCardState? State { get; set; }

        [JsonProperty("nickname")]
        public string? Nickname { get; set; } = null;

        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; } = null;

        [JsonProperty("billingAddress")]
        public BillingAddress? BillingAddress { get; set; } = null;
    }
}