//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum WalletTransactionSourceType
    {
        [JsonProperty("transfer")]
        Transfer,
        [JsonProperty("dispute")]
        Dispute,
        [JsonProperty("issuing-card-transaction")]
        IssuingCardTransaction,
        [JsonProperty("issuing-authorization")]
        IssuingAuthorization,
        [JsonProperty("sweep")]
        Sweep,
        [JsonProperty("adjustment")]
        Adjustment,
        [JsonProperty("fee")]
        Fee,
        [JsonProperty("residual")]
        Residual,
    }

    public static class WalletTransactionSourceTypeExtension
    {
        public static string Value(this WalletTransactionSourceType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static WalletTransactionSourceType ToEnum(this string value)
        {
            foreach(var field in typeof(WalletTransactionSourceType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is WalletTransactionSourceType)
                    {
                        return (WalletTransactionSourceType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum WalletTransactionSourceType");
        }
    }

}