//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Moov.Sdk.Models.Components
{
    using Moov.Sdk.Models.Components;
    using Moov.Sdk.Utils;
    using Newtonsoft.Json;

    public class WebhookDataCaptureUpdated
    {
        /// <summary>
        /// The accountID which facilitated the transfer the capture belongs to.
        /// </summary>
        [JsonProperty("accountID")]
        public string AccountID { get; set; } = default!;

        /// <summary>
        /// The transfer the capture belongs to.
        /// </summary>
        [JsonProperty("transferID")]
        public string TransferID { get; set; } = default!;

        [JsonProperty("captureID")]
        public string CaptureID { get; set; } = default!;

        [JsonProperty("status")]
        public CaptureStatus Status { get; set; } = default!;
    }
}